# Generated by Django 2.2.5 on 2019-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_subset_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
    ]
