# Generated by Django 2.2.5 on 2019-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
