# Generated by Django 2.2.5 on 2019-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pendig'), ('D', 'Done')], default='A', max_length=1),
        ),
    ]
