# Generated by Django 2.2.5 on 2019-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
