# Generated by Django 2.2.5 on 2019-09-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_subset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subset',
            old_name='todo_id',
            new_name='todo',
        ),
    ]
