# Generated by Django 2.2.5 on 2019-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190922_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.CharField(choices=[('R', 'Regular'), ('O', 'Overdue'), ('N', 'NearOverdue')], default='R', max_length=1),
        ),
    ]
